# Generated by Django 5.2.7 on 2025-10-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adreess',
            new_name='address',
        ),
    ]
