# Generated by Django 5.2.7 on 2025-10-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createad_at',
            new_name='created_at',
        ),
    ]
