# Generated by Django 5.2.7 on 2025-10-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
