# Generated by Django 5.2.7 on 2025-11-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
